name: VerionCore
version: '${project.version}'
main: core.luuh.verioncore.VerionCore
api-version: 1.16
authors: [ ItsLuuh ]
description: Based Core Essential
commands:
  core:
    description: Dimostra l'appartenenza del plugin
  fly:
    description: Gestisci la fly nel server
  gamemode:
    description: Gestisci la gamemode nel server
    aliases:
      - gm
      - gamem
      - gmode
  gmc:
    description: Gestisci la creative nel server
    aliases:
      - gm1
      - gmode1
      - gamem1
  gms:
    description: Gestisci la survival nel server
    aliases:
      - gm0
      - gmode0
      - gamem0
  gma:
    description: Gestisci la adventure nel server
    aliases:
      - gm2
      - gmode2
      - gamem2
  gmsp:
    description: Gestisci la spectator nel server
    aliases:
      - gm3
      - gmode3
      - gamem3
  setspawn:
    description: Imposta lo spawn del server
  spawn:
    description: Teletrasporto allo spawn del server